name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: node12 # You can choose the appropriate Node.js version

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12'  # Set to the Node.js version you're using

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
