name: Run Tests

on:
  push:
    branches:
      - main  # Adjust this branch name if you're working on a different branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Or any other environment that works for your project

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set this to the version of Node you're using, '16' is fine

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
